import type { MenuItemType } from '../menu';

/**
 * Generated by `npm run import:renova -- <export.json>`.
 * Keep this file committed so the demo builds before the first catalog import.
 */
export const VINTAGEDEALERS_ITEMS: MenuItemType[] = [];
